{% set name = "pyModelChecking" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 558afb5d0469cc800b9fc2329157ec6c3c0ee7c67138eb8cb864418a6b4ce842

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark-parser
    - python >=3.6

test:
  imports:
    - pyModelChecking
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/albertocasagrande/pyModelChecking
  summary: A simple Python model checking package
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - GPLv2.txt
  doc_url: https://pymodelchecking.readthedocs.io/

extra:
  recipe-maintainers:
    - xtrojak
